[project]
name = "tinyvlm"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.6.0",
    "huggingface-hub>=0.33.2",
    "numpy>=2.3.1",
    "pillow>=11.3.0",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "transformers>=4.53.1",
    "wandb>=0.21.0",
]
